name: CI -> Deploy to funktion-und-graph.ch
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload from public_html via FTP
        run: |
          sudo apt-get install -y ftp
          ftp -inv ${{ secrets.FTP_HOST }} <<EOF
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          cd funktion-und-graph.ch/public_html
          mput *
          bye
          EOF